version: '3.8'

services:
  ai-news-scraper:
    build: .
    container_name: ai-news-scraper
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-haiku-20240307}
      - DATABASE_PATH=/app/data/ai_news.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-60}
    volumes:
      - ai_news_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-news-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: ai-news-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ai-news-scraper
    networks:
      - ai-news-network

volumes:
  ai_news_data:
    driver: local

networks:
  ai-news-network:
    driver: bridge